[book]
name = "So happens that in Berlin, a man gave birth to himself"
authors = ["Kundai Farai Sachikonye"]
description = "A complete epstemological framework on predeterminism"
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/fullscreen-triangle/buhera-printing-press"
edit-url-template = "https://github.com/fullscreen-triangle/buhera-printing-press/edit/main/{path}"

[preprocessor.links]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3 